import swaggerJsdoc from 'swagger-jsdoc';

export const openapiSpec = swaggerJsdoc({
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'SubBase Take-Home API',
      version: '1.0.0',
      description:
        "REST API for the SubBase take-home starter environment. Provides read/write access to the existing SubBase domain: vendors, materials, projects, users, purchase orders, deliveries, and inventory. The rental-equipment domain is intentionally not modelled — that is the candidate's deliverable.",
    },
    servers: [{ url: '/', description: 'Same origin' }],
    tags: [
      { name: 'Health' },
      { name: 'Users' },
      { name: 'Vendors' },
      { name: 'Materials' },
      { name: 'Projects' },
      { name: 'Purchase Orders' },
      { name: 'Deliveries' },
      { name: 'Inventory' },
      { name: 'Equipment' },
      { name: 'Equipment Assignments' },
      { name: 'Equipment Events' },
    ],
    components: {
      schemas: {
        Error: {
          type: 'object',
          properties: {
            error: { type: 'string' },
            details: { type: 'object', nullable: true },
          },
        },
        User: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            email: { type: 'string', format: 'email' },
            role: {
              type: 'string',
              enum: ['PROCUREMENT', 'SUPERINTENDENT', 'FLEET_MANAGER'],
            },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Vendor: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            category: {
              type: 'string',
              enum: [
                'CONCRETE',
                'REBAR',
                'FASTENERS',
                'LUMBER',
                'ELECTRICAL',
                'TOOLS_RENTAL_EXTERNAL',
              ],
            },
            contactEmail: { type: 'string' },
            contactPhone: { type: 'string' },
            paymentTerms: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Material: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            sku: { type: 'string' },
            name: { type: 'string' },
            category: { type: 'string' },
            unit: {
              type: 'string',
              enum: ['EA', 'LF', 'CY', 'LB', 'BAG'],
            },
            unitPrice: { type: 'number' },
            vendorId: { type: 'string' },
            vendor: { $ref: '#/components/schemas/Vendor' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        Project: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            name: { type: 'string' },
            customer: { type: 'string' },
            address: { type: 'string' },
            status: {
              type: 'string',
              enum: ['ACTIVE', 'COMPLETED', 'ON_HOLD'],
            },
            startDate: { type: 'string', format: 'date-time' },
            projectedEndDate: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        PurchaseOrderLine: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            purchaseOrderId: { type: 'string' },
            materialId: { type: 'string' },
            quantity: { type: 'number' },
            unitPrice: { type: 'number' },
            lineTotal: { type: 'number' },
            material: { $ref: '#/components/schemas/Material' },
          },
        },
        PurchaseOrder: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            poNumber: { type: 'string' },
            status: {
              type: 'string',
              enum: ['DRAFT', 'SUBMITTED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CLOSED'],
            },
            total: { type: 'number' },
            expectedDelivery: { type: 'string', format: 'date-time', nullable: true },
            vendorId: { type: 'string' },
            projectId: { type: 'string' },
            createdById: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            vendor: { $ref: '#/components/schemas/Vendor' },
            project: { $ref: '#/components/schemas/Project' },
            createdBy: { $ref: '#/components/schemas/User' },
            lines: {
              type: 'array',
              items: { $ref: '#/components/schemas/PurchaseOrderLine' },
            },
          },
        },
        DeliveryLine: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            deliveryId: { type: 'string' },
            purchaseOrderLineId: { type: 'string' },
            quantityReceived: { type: 'number' },
          },
        },
        Delivery: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            deliveredAt: { type: 'string', format: 'date-time' },
            status: {
              type: 'string',
              enum: ['PENDING', 'PARTIAL', 'COMPLETE'],
            },
            notes: { type: 'string', nullable: true },
            purchaseOrderId: { type: 'string' },
            receivedById: { type: 'string' },
            purchaseOrder: { $ref: '#/components/schemas/PurchaseOrder' },
            receivedBy: { $ref: '#/components/schemas/User' },
            lines: {
              type: 'array',
              items: { $ref: '#/components/schemas/DeliveryLine' },
            },
          },
        },
        InventoryItem: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            materialId: { type: 'string' },
            projectId: { type: 'string' },
            quantityOnHand: { type: 'number' },
            lastUpdatedAt: { type: 'string', format: 'date-time' },
            material: { $ref: '#/components/schemas/Material' },
            project: { $ref: '#/components/schemas/Project' },
          },
        },
        InventoryTransaction: {
          type: 'object',
          properties: {
            id: { type: 'string' },
            type: { type: 'string', enum: ['IN', 'OUT', 'TRANSFER'] },
            quantity: { type: 'number' },
            reference: { type: 'string', nullable: true },
            materialId: { type: 'string' },
            projectId: { type: 'string' },
            fromProjectId: { type: 'string', nullable: true },
            userId: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
            material: { $ref: '#/components/schemas/Material' },
            project: { $ref: '#/components/schemas/Project' },
            fromProject: { $ref: '#/components/schemas/Project' },
            user: { $ref: '#/components/schemas/User' },
          },
        },
        Equipment: {
          type: 'object',
          description:
            'Owned or rented machine. currentProjectId/currentProject, isOverdue, daysOverdue, wasteToDate and utilizationPct are DERIVED in src/lib/rentalMath.js, not stored.',
          properties: {
            id: { type: 'string' },
            assetTag: { type: 'string' },
            name: { type: 'string' },
            category: {
              type: 'string',
              enum: [
                'SKID_STEER',
                'LIFT',
                'COMPACTOR',
                'GENERATOR',
                'PUMP',
                'SAW',
                'TROWEL',
                'BREAKER',
                'EXCAVATOR',
                'OTHER',
              ],
            },
            ownership: { type: 'string', enum: ['OWNED', 'RENTED'] },
            status: {
              type: 'string',
              enum: ['AVAILABLE', 'IN_USE', 'IDLE', 'DOWN', 'RETURNED'],
            },
            dailyRate: { type: 'number' },
            make: { type: 'string', nullable: true },
            model: { type: 'string', nullable: true },
            year: { type: 'integer', nullable: true },
            vendorId: { type: 'string', nullable: true },
            purchaseOrderId: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            currentProjectId: {
              type: 'string',
              nullable: true,
              description: 'Derived from ACTIVE assignment',
            },
            isOverdue: { type: 'boolean', description: 'Derived' },
            daysOverdue: { type: 'integer', description: 'Derived' },
            wasteToDate: { type: 'number', description: 'Derived: daysOverdue x dailyRate' },
            utilizationPct: {
              type: 'integer',
              description: 'Derived: deployed days / available days',
            },
          },
        },
        EquipmentAssignment: {
          type: 'object',
          description:
            'A machine committed to a project for a date range. Canonical rental-date grain.',
          properties: {
            id: { type: 'string' },
            equipmentId: { type: 'string' },
            projectId: { type: 'string' },
            startDate: { type: 'string', format: 'date-time' },
            expectedEndDate: { type: 'string', format: 'date-time' },
            actualEndDate: { type: 'string', format: 'date-time', nullable: true },
            status: { type: 'string', enum: ['SCHEDULED', 'ACTIVE', 'RETURNED'] },
            dailyRate: { type: 'number', description: 'Snapshot at assignment time' },
            notes: { type: 'string', nullable: true },
            createdById: { type: 'string' },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
        EquipmentEvent: {
          type: 'object',
          description:
            'Field/lifecycle event. occurredAt = field time; syncedAt = server receipt (offline gap).',
          properties: {
            id: { type: 'string' },
            type: {
              type: 'string',
              enum: ['CHECK_OUT', 'CHECK_IN', 'OFF_RENT', 'DOWN', 'TRANSFER'],
            },
            condition: {
              type: 'string',
              enum: ['GOOD', 'DAMAGED', 'NEEDS_SERVICE'],
              nullable: true,
            },
            photoUrl: { type: 'string', nullable: true },
            notes: { type: 'string', nullable: true },
            equipmentId: { type: 'string' },
            assignmentId: { type: 'string', nullable: true },
            projectId: { type: 'string', nullable: true },
            userId: { type: 'string' },
            occurredAt: { type: 'string', format: 'date-time' },
            syncedAt: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
  },
  apis: ['./src/routes/*.js'],
});
